src/conversion.rs
src/lazy/dataframe.rs
src/lib.rs
src/series.rs

Updated error messages:
- to mirror the match blocks
- to be consistent with `{}` around the enum values in the message

fix: Update conversion errors

---

__tests__/lazy_functions.test.ts
polars/datatypes/datatype.ts
polars/datatypes/field.ts
polars/index.ts
polars/lazy/expr.ts
polars/lazy/expr/list.ts
polars/lazy/functions.ts
polars/shared_traits.ts

adds `pl.element()`, and dtype constructors`pl.Null`, and `pl.Struct(field)`
also cleans up `DataType` string/js repr a bit.

feat: pl.element() and additional dtype constructors

---

README.md
polars/dataframe.ts
polars/lazy/dataframe.ts

If you have any suggestions how to best check / generate the tsdoc locally, I'm happy to learn.
For instance I think the @link of the join in dataframe should be JoinBaseOptions instead of JoinOptions but it did not find a easy way to check this myself

docs: fix broken link and update join documentation

---

Cargo.toml
src/dataframe.rs

temporarily disable these functions until i can further investigate root cause.

disable tsfn calls with null. 

---

__tests__/io.test.ts
polars/io.ts
src/dataframe.rs

Old vertion provide dtype property in ReadCsvOptions（polars/io.ts）, but is not implement in src/dataframe.rs, so it implement dtypes option for read_csv function and due to it is a collection of column type defination, so change name to dtypes

feat: 🎸 support dtypes option for read_csv function

---

__tests__/io.test.ts
src/dataframe.rs

As pr #64, support dtypes option for readCSV but not implement for read_csv when first param is buffer, so fix it.

fix: 🐛 dtypes should take effect on readCSV for buffer input

---

__tests__/dataframe.test.ts
src/conversion.rs

Fixing date to time conversion to address toRecords date issue highlighted by #48

Fixing date to time conversion

---

.github/workflows/docs.yaml
.github/workflows/test-js.yaml
README.md
package.json

Adding Node 20 and removing Node 16 and 17 to close #106 
Upgrading toolchain to match rust-toolchain

Adding Node 20

---

.github/workflows/create-js-release.yaml
.github/workflows/docs.yaml
.github/workflows/test-js.yaml
package.json
polars/dataframe.ts
polars/index.ts
polars/series/index.ts
yarn.lock

Upgrading actions
Adding bum step to CI to close #113

Adding bun step to CI

---

__tests__/dataframe.test.ts
polars/internals/construction.ts

closes #20
note: the explicit schema is required if you want to retain the null values.
```js
// this will drop the null column if all values of "c" are null
> pl.DataFrame([{a:1, b:2, c:null}])
shape: (1, 2)
┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ f64 ┆ f64 │
╞═════╪═════╡
│ 1.0 ┆ 2.0 │
└─────┴─────┘
```
```js
// this will strictly use the schema provided.
> pl.DataFrame([{a:1, b:2, c:null}], {
schema: { a: pl.Int32, b: pl.Int32, c: pl.Utf8 },
orient: "row",
});
shape: (1, 3)
┌─────┬─────┬──────┐
│ a   ┆ b   ┆ c    │
│ --- ┆ --- ┆ ---  │
│ i32 ┆ i32 ┆ str  │
╞═════╪═════╪══════╡
│ 1   ┆ 2   ┆ null │
└─────┴─────┴──────┘
```

fix: from_rows

---

README.md
__tests__/dataframe.test.ts
polars/dataframe.ts
polars/html.ts

Hi! 👋🏻
This introduces a basic way to display Polars DataFrames from a deno kernel in a Jupyter Notebook.
While I've [baked it into `display.js`](https://github.com/rgbkrk/display.js/blob/main/test-notebooks/polars-df.ipynb), which is on its way to be part of `Deno` itself (https://github.com/denoland/deno/pull/20819), I'd love to get a solid implementation inside of `nodejs-polars`. There are two mediatypes exported here via the [Rich Content Output Symbol, `Symbol.for("Jupyter.display")`](https://docs.deno.com/runtime/manual/tools/jupyter#rich-content-output)
* `text/html` - a standard static table we're all pretty used to
* `application/vnd.dataresource+json` - Row oriented JSON for frontends to implement scrollable grids for a table (and additional data visualization).
Here's an …

create built in way to visualize dataframe in Jupyter

---

README.md
polars/lazy/functions.ts

Converting docs from Python to TS/JS

Fixing docs

---

.github/workflows/create-js-release.yaml
__tests__/dataframe.test.ts
__tests__/expr.test.ts
__tests__/lazyframe.test.ts
biome.json
package.json
polars/dataframe.ts
polars/internals/construction.ts
polars/lazy/dataframe.ts
polars/series/index.ts
polars/shared_traits.ts
yarn.lock

Upgrading biome to 1.3.1 and fixing linting errors
Fixing Android release build

Upgrading biome and fixing linting errors

---

__tests__/expr.test.ts
polars/lazy/expr/index.ts

unique expr with maintainOrder was calling an unknown function. This PR fixes unique expr with maintainOrder option.

Fixing unique expr with maintainOrder option

---

__tests__/io.test.ts
__tests__/setup.ts
polars/dataframe.ts
polars/datatypes/datatype.ts
polars/datatypes/field.ts
polars/groupby.ts
polars/internals/construction.ts
polars/io.ts
polars/lazy/dataframe.ts
polars/lazy/expr/index.ts
polars/lazy/expr/list.ts
polars/lazy/expr/string.ts
polars/lazy/functions.ts
polars/series/index.ts
src/conversion.rs
src/dataframe.rs
src/datatypes.rs
src/lazy/dataframe.rs
src/lazy/dsl.rs
src/list_construction.rs
src/prelude.rs
src/series.rs

Fixing skip_rows bug to close #146 
Adding scanCSV options

Fixing skip_rows bug and adding scanCSV options

---

.github/workflows/create-js-release.yaml
.github/workflows/test-js.yaml
__tests__/setup.ts
package.json
polars/dataframe.ts
polars/datatypes/datatype.ts
polars/datatypes/field.ts
polars/groupby.ts
polars/internals/construction.ts
polars/io.ts
polars/lazy/dataframe.ts
polars/lazy/expr/index.ts
polars/lazy/expr/list.ts
polars/lazy/expr/string.ts
polars/lazy/functions.ts
polars/series/index.ts
tsconfig.test.json
yarn.lock

Updating libraries to the latest

Updating libraries

---

__tests__/functions.test.ts
__tests__/series.test.ts
__tests__/setup.ts
polars/dataframe.ts
polars/datatypes/datatype.ts
polars/datatypes/field.ts
polars/groupby.ts
polars/internals/construction.ts
polars/io.ts
polars/lazy/dataframe.ts
polars/lazy/expr/index.ts
polars/lazy/expr/list.ts
polars/lazy/expr/string.ts
polars/lazy/functions.ts
polars/series/index.ts
src/series.rs

Adding error message to date repeat to close #145 
Linting fixes

Adding error message to date repeat

---

polars/dataframe.ts

This patch fixes an issue with `partitionBy` when you call it without any optional arguments.
Since `includeKey` has no default value, calling `df.partitionBy('some_column')` results in the following error:
```
Error: Failed to convert napi value into rust type `bool`
at Proxy.partitionBy (node_modules/nodejs-polars/bin/dataframe.js:309:18)
```
This is caused by the fact that the value being passed for `includeKey` is `undefined`.
This patch reflects the default in the Rust version, which is `includeKey = true`.

fix(partitionBy): set default value for `includeKey`

---

__tests__/dataframe.test.ts
package.json
polars/dataframe.ts
polars/lazy/expr/index.ts
yarn.lock

Adding DF upsample to close #162

Adding DF upsample

---

__tests__/dataframe.test.ts
polars/dataframe.ts

Fix transpose with option columnNames working with arrays

---

__tests__/groupby.test.ts
polars/groupby.ts

1. Replacing groupBy count with len
2. Changing groupBy len/count logic to match Python version
3. Closing #191

Replacing groupBy count with len

---

__tests__/series.test.ts
polars/series/index.ts

Don’t rely solely on `has_validity` to determine whether a series contains nulls
From the [Python documentation](https://docs.pola.rs/py-polars/html/reference/series/api/polars.Series.has_validity.html#polars.Series.has_validity) for `has_validity` (emphasis mine):
> While the absence of a validity bitmask guarantees that a Series does not have `null` values, the converse is not true, eg: **the presence of a bitmask does not mean that there are null values**, as every value of the bitmask could be `false`.
> 
> To confirm that a column has null values use `null_count()`.
This PR modifies the logic for `Series.toTypedArray` (in line with the note quoted above) to check `nullCount()` if the Series `hasValidity()`, rather than relying on the `hasValidity()` check alone.
Closes #206

Check nullCount in Series.toTypedArray

---

polars/lazy/dataframe.ts

some methods incorrectly had return type `any`

Add missing return types on LazyDataFrame

---

__tests__/dataframe.test.ts
__tests__/lazy_functions.test.ts

From the [Jest docs](https://jestjs.io/docs/using-matchers#common-matchers) (emphasis mine):
> `toEqual` ignores object keys with undefined properties, undefined array items, array sparseness, **or object type mismatch. To take these into account use `toStrictEqual` instead.**
Therefore, note the following:
```ts
// this passes:
expect(pl.Bool).toEqual(pl.String);
// this fails:
expect(pl.Bool).toStrictEqual(pl.String);
```
However, several tests currently use `toEqual` to check polars `DataTypes`—these tests are **broken** because they **will not fail** even if the data types don’t match the expectation.
---
In order to fix these tests, I’ve tried to replace `toEqual` with `toStrictEqual` in all the places where DataType comparison was intended (however, it’s very possible I missed some …

Fix broken tests by using toStrictEqual

---

__tests__/dataframe.test.ts
polars/dataframe.ts
src/dataframe.rs

Adding JoinArgs to fix join suffix to close #219

Adding JoinArgs to fix join suffix

---

polars/dataframe.ts
polars/datatypes/datatype.ts
polars/datatypes/index.ts
polars/index.ts
polars/internals/construction.ts
polars/series/index.ts
src/conversion.rs
src/series.rs

example usage
```ts
const s = pl.Series(
"a",
[
[1, 2],
[3, 4],
],
pl.FixedSizeList(pl.Int32, 2),
);
shape: (2,)
Series: 'a' [array[i32, 2]]
[
[1, 2]
[3, 4]
]

feat: add support for 'array' datatype

---

polars/dataframe.ts

"value:" is incorrect in the context of pivot, removed

fix: fixing incorrect example

---

__tests__/functions.test.ts
polars/functions.ts
polars/lazy/dataframe.ts
polars/utils.ts
src/functions.rs

Resolves https://github.com/pola-rs/nodejs-polars/issues/232
Exposes the underlying lazy-compatible `concat`, `concat_lf_horizontal`, and `concat_lf_diagonal` functions in native.
Tried to keep things reasonably inline with existing code. Added tests that verify the behavior 👍

feat: Add concatenation of LazyDataFrames

---

__tests__/expr.test.ts
polars/lazy/expr/index.ts

Adding string to parameters for expr replace function
Adding replace tests

Adding string to parameters for replace function

---

__tests__/dataframe.test.ts
__tests__/lazyframe.test.ts
polars/dataframe.ts
polars/lazy/dataframe.ts

Resolves #235 
The native binding for `DataFrame#sort` looks like:
https://github.com/pola-rs/nodejs-polars/blob/093d4967b3da6e39a8239bf13155587d5941fe99/src/dataframe.rs#L765-L771
The [LazyDataFrame variant](https://github.com/pola-rs/nodejs-polars/blob/093d4967b3da6e39a8239bf13155587d5941fe99/src/lazy/dataframe.rs#L135-L140) also has the same shape.
---
But, the Javascript versions use a hardcoded `nulls_last` value of `true`:
https://github.com/pola-rs/nodejs-polars/blob/093d4967b3da6e39a8239bf13155587d5941fe99/polars/dataframe.ts#L2345
https://github.com/pola-rs/nodejs-polars/blob/093d4967b3da6e39a8239bf13155587d5941fe99/polars/lazy/dataframe.ts#L965
---
Additionally, `DataFrame#sort` has a minor argument bug: `maintain_order` is not passed when using an options object. This bug is …

feat: Support `nulls_last` option in `DataFrame#sort`

---

__tests__/series.test.ts
polars/datatypes/datatype.ts
polars/lazy/functions.ts
polars/series/index.ts

feat: generic `Series`

---

__tests__/dataframe.test.ts
polars/dataframe.ts
src/dataframe.rs

The pivot function now has `on` as the first param instead of `index`, as noted in the [python 1.0 upgrade documentation](https://docs.pola.rs/releases/upgrade/1/#update-resulting-column-names-in-pivot-when-pivoting-by-multiple-values):
> columns has been renamed to on, and is now the first positional argument.
Added some test coverage from examples in docs to capture this. Existing test coverage was using the same column as `index` and `on`, resulting in this not being caught.

fix: update pivot expr on to first param

---

Cargo.toml
__tests__/io.test.ts
polars/dataframe.ts
polars/index.ts
polars/io.ts
src/dataframe.rs

TLDR: Solves https://github.com/pola-rs/nodejs-polars/issues/109
More or less the IPC Stream methods are straight copies of the IPC File (Feather) ones, swapping out the IpcReader, IpcWriter for their streaming equivalents; the API should be identical to py-polars (with the exception of file-like objects as input for read_ipc, read_ipc_stream - not much point adding that until streaming IO is exposed upstream).
I've left the docstrings basically untouched, let me know if you want those tweaked (the `@param` s appear to have drifted over time).

Replicate py-polars API surface for streaming IPC formats

---

__tests__/io.test.ts
src/conversion.rs

Adding null to string dtype conversion to close #262

Adding null to string dtype conversion

---

__tests__/lazy_functions.test.ts
polars/lazy/functions.ts

Deprecating old arguments in intRange to match `py-polars`

Deprecating old arguments in intRange

---

Cargo.toml
polars/io.ts
polars/types.ts
src/lazy/dataframe.rs

Adding cloud features

---

polars/series/index.ts

Trying to build my project with `"nodejs-polars": "^0.15.0"` as a dependency gives the following error
```
node_modules/nodejs-polars/bin/series/index.d.ts:9:66 - error TS2307: Cannot find module '@polars/datatypes/datatype' or its corresponding type declarations.
9 import type { DTypeToJs, DtypeToJsName, JsToDtype, JsType } from "@polars/datatypes/datatype";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
On inspecting the source TS files I see TS is complaining that the path doesn't exist. 
This bug will not show up in development on this repo because the `@polars` alias is correctly defined in `tsconfig.json` but the distributed source code doesn't know anything about this path alias.
- updated the path
- successfully build my project
- test loading a CSV file
- On branch of the source code I ran …

fix: fix broken path to datatypes causing typescript compilation to fail

---

__tests__/dataframe.test.ts
polars/series/index.ts

Fixing series fold to close #79

Fixing series fold

---

__tests__/dataframe.test.ts
__tests__/io.test.ts
__tests__/lazyframe.test.ts
__tests__/serde.test.ts
biome.json
package.json
polars/dataframe.ts
polars/functions.ts
polars/groupby.ts
polars/index.ts
polars/internals/construction.ts
polars/io.ts
polars/lazy/dataframe.ts
polars/lazy/expr/index.ts
polars/lazy/expr/list.ts
polars/lazy/expr/string.ts
polars/lazy/expr/struct.ts
polars/lazy/functions.ts
polars/lazy/groupby.ts
polars/lazy/whenthen.ts
polars/series/index.ts
polars/series/string.ts
polars/series/struct.ts
polars/shared_traits.ts
polars/utils.ts
yarn.lock

Upgrading biome to latest
Sorting imports as suggested by biome
Adding `node:` prefix to imports as suggested by biome

Upgrading biome

---

__tests__/datelike.test.ts
polars/dataframe.ts
polars/lazy/dataframe.ts
src/lazy/dataframe.rs

This PR aims to support [`nearest` asof join strategy](https://docs.rs/polars/0.43.1/polars/prelude/enum.AsofStrategy.html#variant.Nearest). In brief, it changes:
- Add "nearest" type mapping to AsofStrategy::Nearest
- Add "nearest" option to typescript's typing
- Add testcase
Closes #286

Support "nearest" joinAsof strategy

---

__tests__/io.test.ts
polars/io.ts
polars/lazy/expr/string.ts
polars/series/string.ts

Setting inferSchemaLength = 0 when null to close #279

Setting inferSchemaLength = 0 when null

---

__tests__/dataframe.test.ts
__tests__/expr.test.ts
__tests__/series.test.ts
polars/dataframe.ts
polars/datatypes/datatype.ts
polars/lazy/expr/string.ts
polars/lazy/functions.ts
polars/series/index.ts
polars/utils.ts

resolves #292. please check individual commits for detail.

feat: generic `DataFrame`

---

polars/types.ts

Adding allowMissingColumns to ScanParquetOptions to close #284

Adding allowMissingColumns to ScanParquetOptions

---

__tests__/dataframe.test.ts
__tests__/series.test.ts
polars/dataframe.ts
polars/groupby.ts
polars/lazy/dataframe.ts
polars/lazy/expr/string.ts
polars/series/index.ts
polars/series/string.ts
src/conversion.rs

Removing deprecated methods

---

__tests__/expr.test.ts
__tests__/series.test.ts
polars/lazy/expr/datetime.ts
polars/lazy/expr/index.ts
polars/lazy/expr/list.ts
polars/lazy/expr/string.ts
polars/lazy/expr/struct.ts
polars/series/datetime.ts
polars/series/index.ts
polars/series/list.ts
polars/series/string.ts
polars/series/struct.ts
src/lazy/dsl.rs

New functions in src\lazy\dsl.rs
- add implode, str_strip_chars, str_starts_with, str_ends_with
- add expression support in str_replace and str_replace_all
- add struct_field_by_index, struct_with_fields
Update documentation for Series in polars/series/*
- replaced ListNamespace by SeriesListFunctions (ListSeries in doc) and StringNamespace by SeriesStringFunctions (StringSeries in doc)
- renamed SeriesDateFunctions by DatetimeSeries and SeriesStructFunctions by StructSeries
_Unfortunately Namespaces are not consistent between Series and Lazy with current polars sources (or I didn't succeed to align them).
So not sure that Namespaces in shared_traits are very usefull._
Update implementation and documentation for Expr in polars/lazy/expr/*
- convert ExprDateTime from type to interface and …

Add new functions to Series and Expressions, some docs update

---

__tests__/io.test.ts
polars/io.ts
src/dataframe.rs

Renaming commentChar to commentPrefix to match PY-Polars and to close #334

bug: Renaming commentChar to commentPrefix

---

__tests__/type.test.ts
package.json
polars/dataframe.ts
polars/datatypes/conversion.ts
polars/datatypes/datatype.ts
polars/datatypes/index.ts
polars/lazy/dataframe.ts
polars/series/index.ts
polars/series/string.ts
polars/types.ts
yarn.lock

This is a breaking change.
It feels more natural to express the genericness of a DataFrame through its schema rather than its similarity to a Record of Series. For example, joins then can be computed more easily, as we don't need to unpack each Series to rename them.

feat: switch DataFrame generic to its schema
