pola-rs/nodejs-polars

polars/io.ts
src/lazy/dataframe.rs

exposes more of the lower level scanjson options to JS

add more options for "scanJson" function

---

Cargo.toml
README.md
__tests__/dataframe.test.ts
__tests__/series.test.ts
polars/dataframe.ts
polars/lazy/functions.ts
polars/series/series.ts
src/conversion.rs
src/dataframe.rs
src/lazy/dataframe.rs
src/lazy/dsl.rs
src/lib.rs
src/series.rs
src/set.rs

feat[misc]: add latest changes from upstream

---

polars/series/series.ts

Fixes: https://github.com/pola-rs/nodejs-polars/issues/25

fix: issue with scoped module

---

polars/lazy/dataframe.ts

fix: add anti and semi join type 

---

package-lock.json
polars/io.ts
sample.ts

In response to the issue I opened earlier today (#37 ):
-  Added interfaces to io.ts functions such that they fit the options that appear in the docstring, and in the default options
-  Used this interfaces to cast the types of the options of each function - using the `Partial` utility type.
Should I create a base options interface and for each function extend? If so, where can I find a good description of all possible common options? And then, of each individual option?
Open to comments and suggestions! Also my first contribuition!

Added option interfaces to io functions for intellisense.

---

__tests__/dataframe.test.ts
src/dataframe.rs

Adding check for null object element when creating a DF

Adding check for null element in a DF

---

__tests__/lazy_functions.test.ts
polars/index.ts
polars/lazy/functions.ts

Adding missing intRanges function and tests

Adding intRanges

---

__tests__/dataframe.test.ts
polars/lazy/functions.ts
src/conversion.rs

Adding categorical ToNapiValue conversion  to resolve #96

Adding categorical ToNapiValue

---

README.md

Adding webpack node-loader line to readme to close #13

Adding webpack node-loader line to readme

---

__tests__/functions.test.ts
polars/index.ts
polars/lazy/functions.ts
src/lazy/dsl.rs

Fixed the problem in #95, where anyHorizontal/allHorizontal did not exist. Since sumHorizontal, minHorizonal/maxHorizontal also do not exist and are in the same main commit, I will add them when I figure out how to fix it.

Adding allHorizontal/anyHorizontal

---

__tests__/io.test.ts
polars/io.ts

Fixing documentation for readJSONStream to close #101  
Adding a test for readJSONStream with lines to catch this issue in the future.

Fixing documentation for readJSONStream, adding a test for readJSONStream with lines

---

__tests__/io.test.ts
polars/io.ts

Fixing quoteChar typo to close #116

Fixing quoteChar typo

---

__tests__/functions.test.ts
polars/functions.ts
polars/types.ts
src/functions.rs

Adding diagonal how to DF concat to close #124

Adding diagonal how to DF concat

---

__tests__/functions.test.ts
polars/index.ts
polars/lazy/functions.ts
src/lazy/dsl.rs

Three weeks ago I had this done, and I just forgot to submit it. Adding on to any/all horizontal, essentially just different functions same idea. Dataframe/series function

Adding sum, min and max horizontal

---

__tests__/expr.test.ts
polars/shared_traits.ts
polars/types.ts
src/conversion.rs

Adding ddof to JsRollingOptions to close #127

Adding ddof to JsRollingOptions

---

README.md

Fixing svg links in top section of Readme
Closing #138

Fixing top section of Readme

---

__tests__/lazyframe.test.ts
polars/lazy/dataframe.ts
polars/types.ts
src/conversion.rs
src/lazy/dataframe.rs

Adding lazy frame sinkParquet function

Adding ldf sinkParquet

---

polars/dataframe.ts

Fixing documentation for DF `.eq` string expr

Fixing documentation for DF `.eq` string expr

---

__tests__/series.test.ts
polars/series/index.ts

Adding Series valueCounts implementation to close #165

Adding Series valueCounts implementation

---

src/conversion.rs
src/dataframe.rs
src/lazy/dataframe.rs
src/lazy/dsl.rs
src/list_construction.rs

Removing unused imports

---

__tests__/lazy_functions.test.ts
polars/dataframe.ts
polars/index.ts

closes https://github.com/pola-rs/nodejs-polars/issues/186

fix: cjs compatibility

---

__tests__/dataframe.test.ts
polars/dataframe.ts

closes https://github.com/pola-rs/nodejs-polars/issues/170

fix: df schema fix

---

__tests__/expr.test.ts
polars/lazy/expr/index.ts

Adding arc[cos,sin.tan] functions

Adding arc functions

---

__tests__/dataframe.test.ts
src/conversion.rs

Implement missing `str_to_polarstype` case for String

---

Cargo.toml
package.json

0.12.0 release got botched somehow. Re-releasing.

chore: bump version

---

__tests__/expr.test.ts
polars/datatypes/datatype.ts
polars/index.ts
polars/lazy/expr/string.ts
polars/series/string.ts
polars/shared_traits.ts

closes https://github.com/pola-rs/nodejs-polars/issues/237

fix: make pl.Datetime work uninitialized

---

__tests__/expr.test.ts
biome.json
polars/index.ts
polars/lazy/functions.ts
src/lazy/dataframe.rs
src/lazy/dsl.rs

Adding expr pl.len() to close #257

Adding expr pl.len()

---

polars/dataframe.ts

Fixing pivot docs and example to close #272

Fixing pivot docs and example

---

polars/dataframe.ts

fix accidentally-deprecated sort method

---

__tests__/expr.test.ts
polars/lazy/expr/string.ts
polars/series/string.ts
polars/shared_traits.ts
src/lazy/dsl.rs

Allowing expr in contains to match Python syntax to close #311

Allowing expr in contains

---

Cargo.toml
npm/android-arm64/package.json
npm/darwin-arm64/package.json
npm/darwin-x64/package.json
npm/linux-arm64-gnu/package.json
npm/linux-arm64-musl/package.json
npm/linux-x64-gnu/package.json
npm/linux-x64-musl/package.json
npm/win32-x64-msvc/package.json
package.json
yarn.lock

Upgrading `@napi-rs/cli` to v3
Bumping version in `npm/*/package.json`

chore: Upgrading napi-rs/cli

---

Cargo.toml

Turning off type-def feature and upgrading napi-build

chore: Upgrading napi-build

---

.github/workflows/create-js-release.yaml
.github/workflows/docs.yaml
.github/workflows/test-js.yaml
Cargo.toml
npm/android-arm64/package.json
npm/darwin-arm64/package.json
npm/darwin-x64/package.json
npm/linux-arm64-gnu/package.json
npm/linux-arm64-musl/package.json
npm/linux-x64-gnu/package.json
npm/linux-x64-musl/package.json
npm/win32-x64-msvc/package.json
package.json

Adding new `--use-napi-cross` flag
Dropping Node 18 testing
Using python version: 3.13 for docs
Release v0.20.1

Updating GHA yaml

---

Cargo.toml
__tests__/expr.test.ts
__tests__/series.test.ts
package.json
polars/cfg.ts
polars/lazy/expr/index.ts
polars/lazy/expr/string.ts
polars/series/index.ts
polars/series/string.ts
src/conversion.rs
src/dataframe.rs
src/datatypes.rs
src/lazy/dataframe.rs
src/lazy/dsl.rs
src/lib.rs
src/series.rs
yarn.lock

chore: Upgrading rs->0.50

---

__tests__/lazyframe.test.ts
polars/lazy/dataframe.ts
polars/types.ts
src/conversion.rs
src/lazy/dataframe.rs

Adding sinkNdJson and sinkIpc to lazyDf to close #353

enh: Adding sinkNdJson and sinkIpc

---

Cargo.toml
__tests__/series.test.ts
package.json
polars/dataframe.ts
yarn.lock

Bumping:
- napi
- biome
- typedoc

chore: Bumping packages

---

__tests__/config.test.ts
polars/cfg.ts
src/cfg.rs
src/lib.rs

Fixing `pl.Config` by setting envs in Rust since Nodejs `process.env` did not get passed to Rust.

bug: Fixing pl.Config
